#!/bin/bash

[[ "$1" == *.*.* ]] ||
{
    echo "Usage: $0 #.#.#"
    exit 1
}

cd "$(dirname "$0")"/..

perl -p -i -e "s/^(\s*default_version\s+=\s+')[^']*('.*)/\${1}$1\${2}/" cyanaudit.control
perl -p -e "s/CYANAUDIT_VERSION/$1/" template_META.json > META.json
[ -f sql/cyanaudit--${1}.sql ] || cp -v sql/cyanaudit.sql sql/cyanaudit--${1}.sql
ln -sf cyanaudit--${1}.sql sql/cyanaudit.sql


