#!/bin/bash

[[ "$1" == *.*.* ]] ||
{
    echo "Usage: $0 #.#.#"
    exit 1
}

cd "$(dirname "$0")"/..

perl -p -i -e "s/^(\s*default_version\s+=\s+')[^']*('.*)/\${1}$1\${2}/" cyanaudit.control
perl -p -i -e "s/(\"version\": \")[^\"]*(\".*cyanaudit)/\${1}$1\${2}/" META.json

